version: '3.4'

services:
  #kafka
  su-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: su-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000

  su-broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: su-broker
    restart: always
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9192:9192"
    depends_on:
      - su-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'su-zookeeper:2183'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://su-broker:9192,PLAINTEXT_INTERNAL://su-broker:29192
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  #monitor
  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.monitor
    depends_on:
      - su-broker   

  #outside device stuff
  scada:
    image: scada
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.scada
    ports:
      - "6069:6069"   

  protection:
    image: protection
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.protection_system
    ports:
      - "6068:6068"

#inside device staff
  auth-tech:
    image: auth-tech
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.auth-tech
    depends_on:
      - monitor
      - su-broker 
    ports:
      - "6071:6071"   

  auth-sec:
    image: auth-sec
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.auth-sec
    depends_on:
      - su-broker
      - monitor
    ports:
      - "6072:6072" 

  downloader:
      image: downloader
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.downloader    
      depends_on:
        - auth-tech
        - auth-sec
        - su-broker
        - monitor

  writer_upd:
      image: writer_upd
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.writer_upd    
      depends_on:
        - su-broker
        - downloader
        - monitor

  validator_upd:
      image: validator_upd
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.validator_upd    
      depends_on:
        - su-broker
        - writer_upd
        - monitor

  update:
      image: update
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.update    
      depends_on:
        - su-broker
        - validator_upd
        - monitor
  
  input:
      image: input
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.input    
      depends_on:
        - su-broker
        - auth-tech
        - auth-sec
        - monitor
  
  writer_set:
      image: writer_set
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.writer_set   
      depends_on:
        - su-broker
        - input
        - monitor

  settings:
      image: settings
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.settings    
      depends_on:
        - su-broker
        - writer_set
        - monitor
  
  hash:
      image: hash
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.hash    
      depends_on:
        - su-broker
        - monitor

  apd:
      image: apd
      build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.ADP    
      depends_on:
        - su-broker
        - monitor
        - settings
  